name: cd

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            apoppe/logme-backend-app:1.0.1
      -
        name: Deploy on vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PASSWORD }}
          script: cd ~/Projects/dockerTest; docker stop dockertest-db-1; docker stop dockertest-app-1; docker image rm apoppe/logme-backend-app:latest -f; docker compose up -d