name: logme-backend-test

on:
    push:
      branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
    # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]
    steps:
      - name: fail
        run: exit 1
        continue-on-error: false
      - name: dont
        run: echo shouldnt be here
      - uses: actions/checkout@master
      - name: Initialize Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pytest
      - name: Run tests
        run: pytest
        continue-on-error: false
        env:
        # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          DB_TEST_NAME: postgres